name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '⬆️ Dependency upgrades'
    labels:
      - 'bump'
      - 'dependencies'
  - title: '📝 Kontraktendringer'
    labels:
      - 'domene/kontrakt'

autolabeler:
  - label: 'chore'
    title:
      - '/^chore:/i'
    files:
      - '*.md'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix:/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/^feature:/i'
    body:
      - '/^[A-Z]{3,8}-[0-9]{1,4}:/'
  - label: 'domene/kontrakt'
    files:
      - 'kontrakter/src/main/**'
  - label: 'app'
    files:
       - 'app/src/main/**'
template: |
  ## What's Changed
  $CHANGES
