ALTER TABLE uttaksperiode ADD COLUMN landkode VARCHAR(3);
ALTER TABLE uttaksperiode ADD COLUMN utenlandsopphold_aarsak VARCHAR(127) DEFAULT 'INGEN';
ALTER TABLE uttaksperiode
ADD CONSTRAINT utenlandsopphold_aarsak_regel
CHECK (utenlandsopphold_aarsak IN (
    'BARNET_INNLAGT_I_HELSEINSTITUSJON_FOR_NORSK_OFFENTLIG_REGNING',
    'BARNET_INNLAGT_I_HELSEINSTITUSJON_DEKKET_ETTER_AVTALE_MED_ET_ANNET_LAND_OM_TRYGD',
    'INGEN'
));