package no.nav.pleiepengerbarn.uttak.regler

enum class Valideringsfeil{
    //Gjelder Uttaksgrunnlag
    BEHANDLING_UUID_FORMATFEIL,
    BEHANDLING_UUID_FORMATFEIL_I_KRAVPRIORITET,
    ARBEIDSFORHOLD_ER_IKKE_UNIKE,
    OVERLAPP_MELLOM_ARBEIDSPERIODER,
    OVERLAPP_MELLOM_INNGANGSVILKÅRPERIODER,
    OVERLAPP_MELLOM_FERIEPERIODER,
    OVERLAPP_MELLOM_PLEIEBEHOVPERIODER,
    OVERLAPP_MELLOM_TILSYNSPERIODER,
    OVERLAPP_MELLOM_SØKT_UTTAK,
    OVERLAPP_MELLOM_BEREDSKAPSPERIODER,
    OVERLAPP_MELLOM_NATTEVÅKSPERIODER,
    OVERLAPP_MELLOM_TRUKKET_UTTAKSPERIODER,
    OVERLAPP_MELLOM_SØKT_UTTAK_OG_TRUKKET_UTTAK,
    OVERLAPP_MELLOM_KRAVPRIORITETPERIODER,
    // Gjelder EndrePerioderGrunnlag
    OVERLAPP_MELLOM_PERIODER_IKKE_ER_INNVILGET,
    ULOVLIG_ENDRING_AV_ÅRSAK
}
