package no.nav.pleiepengerbarn.uttak.kontrakter

enum class KnekkpunktType {
    LOVBESTEMT_FERIE,
    PLEIEBEHOV,
    TILSYNSPERIODE,
    BEREDSKAPSPERIODE,
    NATTEVÅKSPERIODE,
    INNGANGSVILKÅR_IKKE_OPPFYLT,
    ANNEN_PARTS_UTTAK,
    EGET_UTTAK_ANNEN_PLEIETRENGENDE,
    FORRIGE_UTTAKPLAN,
    TRUKKET_UTTAK,
    ARBEID,
    SØKERS_DØDSFALL,
    BARNETS_DØDSFALL,
    BARNETS_DØDSFALL_SLUTT_PÅ_RETT,
    SØKERS_ALDER,
    KRAVPRIORITETSPERIODE,
    UTENLANDSOPPHOLD,
    START_SPESIALHÅNDTERING_TILKOMMEN,
    OVERSTYRT_INPUT,
    INNTEKTSGRADERING
}
