apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pleiepenger-barn-uttak
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: k9-sak
        - application: k9-formidling
  webproxy: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /pleiepenger-barn-uttak/internal/actuator/health
    initialDelay: 30
    timeout: 10
    failureThreshold: 27
  readiness:
    path: /pleiepenger-barn-uttak/internal/actuator/info
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      cpu: 2000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 200Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/pleiepenger-barn-uttak/k9saksbehandling
        mountPath: /var/run/secrets/nais.io/vault
  prometheus:
    enabled: true
    path: /pleiepenger-barn-uttak/internal/actuator/prometheus
  secureLogs:
    enabled: true
  ingresses:
    - https://k9-psb-uttak.dev.intern.nav.no
  env:
    - name: APP_NAME
      value: "pleiepenger-barn-uttak"
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: DEFAULTDS_USERNAME
      value: pleiepenger-barn-uttak
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://b27dbvl014.preprod.local:5432/pleiepenger-barn-uttak

      # open telemetry
    - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
      value: "https://elastic-apm.adeo.no"
    - name: "OTEL_METRICS_EXPORTER"
      value: "otlp"
    - name: "OTEL_LOGS_EXPORTER"
      value: "none"
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "service.name=pleiepenger-barn-uttak,service.version=pleiepenger-barn-uttak,deployment.environment=q"
    - name: "OTEL_TRACES_EXPORTER"
      value: "otlp"

    # Feature toggles
    - name: UTVIDET_LOGGING
      value: "false"
