apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleiepenger-barn-uttak
  namespace: pleiepenger
  labels:
    team: pleiepenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /pleiepenger-barn-uttak/internal/actuator/info
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /pleiepenger-barn-uttak/internal/actuator/info
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /pleiepenger-barn-uttak/internal/actuator/prometheus
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: pleiepenger-barn-uttak
            envVarPrefix: DB
