apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pleiepenger-barn-uttak
  namespace: default
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  team: k9saksbehandling
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /pleiepenger-barn-uttak/internal/actuator/health
    initialDelay: 30
    timeout: 10
  readiness:
    path: /pleiepenger-barn-uttak/internal/actuator/info
    initialDelay: 30
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/pleiepenger-barn-uttak/default
        mountPath: /var/run/secrets/nais.io/vault
  prometheus:
    enabled: true
    path: /pleiepenger-barn-uttak/internal/actuator/prometheus
  secureLogs:
    enabled: true
  ingresses:
    - https://k9-psb-uttak.intern.nav.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: DEFAULTDS_USERNAME
      value: pleiepenger-barn-uttak
    - name: DEFAULTDS_URL
      value: jdbc:postgresql://A01DBVL012.adeo.no:5432/pleiepenger-barn-uttak

    # Appdynamics
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: PROD
