name: "Bygg og deploy"
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.github/*.yml'


jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app-db.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
      upload-image: ${{ github.ref_name != github.event.repository.default_branch }}
      db_schema: pleiepengerbarnuttak_unit
      pg_version: 12
    secrets: inherit

  verdikjede-tester:
    name: Verdikjedetester
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      issues: write
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
    if: ${{github.actor != 'dependabot[bot]'}}
    needs: build-app
    with:
      tag: ${{ needs.build-app.outputs.build-version }}
      suites: "pleiepenger,livetssluttfase,frontend,beregning,pleiepenger-samtidiguttak,pleiepenger-pleietrengende,pleiepenger-soker"
      override_image_artifact_name: ${{ github.ref_name != github.event.repository.default_branch && needs.build-app.outputs.image-artifact-name || null }}
      image_version: ${{ needs.build-app.outputs.build-version }}


  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
      contents: write
    if: github.ref_name == github.event.repository.default_branch
    needs: [build-app, verdikjede-tester]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-fss
      naiserator_file: nais/dev-fss-k9saksbehandling.yml
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
      contents: write
    if: github.ref_name == github.event.repository.default_branch
    needs: [build-app, verdikjede-tester, deploy-dev]
    uses: navikt/sif-gha-workflows/.github/workflows/maven-deploy.yml@main
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-fss
      naiserator_file: nais/prod-fss-k9saksbehandling.yml
    secrets: inherit
