name: Promote
on:
  repository_dispatch:
    types: [ promote-command ]
env:
  NAMESPACE: k9saksbehandling
  IMAGE_BASE: ghcr.io/${{ github.repository }}/server

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Henter informasjon fra issuet
        id: issue_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.get( {
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: ${{ github.event.client_payload.github.payload.issue.number }} })
            .then(response => {
              core.setOutput('sha', response.data.body);
              core.setOutput('title', response.data.title);
            });

      - name: Setter IMAGE som brukes i deploy filen & tag for kode checkout
        run: |
          echo "IMAGE=$IMAGE_BASE:$(echo ${{ steps.issue_comment.outputs.title }} | awk '{print $NF}' | grep -oE '[[:alnum:]_-]+')" >> $GITHUB_ENV
          echo "SHA=$(echo ${{ steps.issue_comment.outputs.sha }} | awk '{print $NF}' | grep -oE '[[:alnum:]_-]+')" >> $GITHUB_ENV
          echo "CLUSTER=$(echo ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }} | grep -oE '[[:alnum:]_-]+')" >> $GITHUB_ENV

      - name: Sjekk ut kode
        uses: actions/checkout@v1
        with:
          ref: ${{ env.TAG }}

      - name: Promoter til cluster og namespace
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: nais/${{ env.CLUSTER }}-${{ env.NAMESPACE }}.yml

      - name: Oppdater kommentar med deployment status ved feil
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.rest.issues.createComment({...issue,
                            body: 'promote til ${{ env.CLUSTER }} ${{ env.NAMESPACE }} feilet'})
            github.rest.issues.addLabels({...issue,
                            labels: ['deployment-failed','${{ env.CLUSTER }}-${{ env.NAMESPACE }}']})

      - name: Oppdater kommentar med deployment status
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue = { owner: context.issue.owner,
                            repo: context.issue.repo,
                            issue_number: ${{ github.event.client_payload.github.payload.issue.number }} }
            github.rest.issues.createComment({...issue,
                            body: 'promote til ${{ env.CLUSTER }} ${{ env.NAMESPACE }} utført'})
            github.rest.issues.addLabels({...issue, labels: ['deployment','${{ env.CLUSTER }}-${{ env.NAMESPACE }}']})
